### ISSUE TITLE
Navigation menu on mobile

### ISSUE THREAD

**Issue by snim2** [PyconUK/pyconuk.org#25]
On my mobile (Samsung Galaxy S3) the navigation menu does not appear when viewing the site in portrait mode, and there is no drop-down. In landscape it looks fine.

In the IRC chat this week ntoll advised pinging @ghickman

**Comment by Lukasa** [comment]
Can confirm, same bug affects my iPhone 6.

**Comment by ghickman** [comment]
@snim2 – thanks for putting this in an issue, I completely forgot to write this up after @inglesp and I discovered it, totally my bad.

We got as far as tracking it down to one of my commits from during DjangoCon. IIRC it was related to [this one](https://github.com/PyconUK/pyconuk.org/commit/4ab0b82ccb9f798d073d3a15ea3b41ce936f3b92) so it's either caused by that or one of the commits near it. I'll try to take a look at this later to work out why my (supposedly unrelated!) changes broke this.

Should anyone else wish to pick this up it seems like the hamburger icons padding/margin top offset isn't being removed in the mobile breakpoint.
